name: Deployment pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize] # the workflow will run when a PR into main is opened or updated

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2 #koodi käyttöön

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Npm install 
        run: npm ci && cd ./frontend && npm ci
        
      - name: Lint
        run: npm run lint

      - name: Test frontend
        run: npm run test:jest

      - name: Build frontend
        run: npm run build:ui

      - name: Deploy to Heroku
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "duckburg-blogs" #Must be unique in Heroku
          heroku_email: ${{secrets.MAIL}}
          healthcheck: "https://duckburg-blogs.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
          
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch